### ISSUE TITLE
Create Level-Up Quiz 

### ISSUE THREAD

**Issue by lzoebaker** [googleinterns/step144-2020#40]
* Create a quiz that links from the game stage page. If the user answers enough question correctly, they are promoted and their game stage is updated to the next stage. If they do not answer enough questions correctly, they are not promoted and remain at their current stage. 
* Promoted/ not promoted message should be displayed to the user when they are redirected back to game stage template.

**Comment by WillHipschman** [comment]
Should include:

1. Create content for Questions/Choices/Correct Choices
2. Add Career Quiz Servlet and objects for question/choice etc.
3. User state should be updated if quiz is answered with appropriate number of correct choices
4. Link servlet to UI from https://github.com/googleinterns/step144-2020/issues/50
